package edu.utap.mypet.reminders

data class Reminder(
        // Auth information
        var name: String = "",
        var ownerUid: String = "",
        // reminder details
        var petPicked: String = "",
        var description: String = "",
        var pickedDate: String = "",
        var pickedTime: String = "",
        var checked: Boolean? = null,
        var otherNotes: String = "",

        //ID generated by firestore, used as primary key
        var reminderID: String = ""
)
