package edu.utap.mypet.todoList

data class ToDoItem(
    var name: String = "",
    var ownerUid: String = "",
    var todoItem: String = "",
    var status: Boolean? = null,
    // rowID is generated by firestore, used as primary key
    var rowID: String = ""
)